ci(turbo): 🦊 CI turbo

diff --git a/.github/workflows/ci-dev.yaml b/.github/workflows/ci-dev.yaml
--- a/.github/workflows/ci-dev.yaml
+++ b/.github/workflows/ci-dev.yaml
@@ -8,18 +8,20 @@ on:
     branches: [dev]
 
 jobs:
-  create-dotenv:
-    name: create environment file
+  build:
+    name: create environment file, test and build
     runs-on: ubuntu-latest
-    # Use the environment specified by the caller (so it pulls the right variables)
     environment: env
     env:
       ENV: ${{ vars.ENV }}
       PORT: ${{ vars.PORT }}
       LOG_LEVEL: ${{ vars.LOG_LEVEL }}
       DATABASE_URL: ${{ secrets.DATABASE_URL }}
-
+      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
+      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
       - name: Print environment variables
         run: |
           echo "ENV: $ENV"
@@ -27,9 +29,7 @@ jobs:
           echo "LOG_LEVEL: $LOG_LEVEL"
           echo "DATABASE_URL: $DATABASE_URL"
 
-      # Write environment variables from GitHub environment to the specified .env file
       - name: Create .env file
-        working-directory: ${{ github.workspace }}
         run: |
           echo "Creating .env file: .env"
           echo "ENV=${{ vars.ENV }}, PORT=${{ vars.PORT }}, LOG_LEVEL=${{ vars.LOG_LEVEL }}, DATABASE_URL=${{ secrets.DATABASE_URL }}"
@@ -37,7 +37,7 @@ jobs:
           echo "PORT=${{ vars.PORT }}" >> .env
           echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> .env
           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
-          
+
       - name: Print project structure
         run: tree -a -L 5 || find . | head -40
 
@@ -47,31 +47,7 @@ jobs:
       - name: Print .env file for debugging
         run: cat .env
 
-      - name: Upload .env as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: hono-env
-          path: .env
-
-  build:
-    needs: create-dotenv
-    name: test and build
-    runs-on: ubuntu-latest
-    env:
-      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
-      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Download .env artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: hono-env
-          path: app/hono/src/environment/
-
-      - name: Print project structure
-        run: tree -a -L 5 || find . | head -40
+    
 
       - name: Setup Node.js environment
         uses: actions/setup-node@v4
@@ -86,7 +62,7 @@ jobs:
 
       # Debug: print the .env file before running tests
       - name: Print .env file for debugging
-        run: cat app/hono/src/environment/.env
+        run: cat app/hono/src/environment/.env || echo ".env not found in app/hono/src/environment/"
 
       - name: Run tests
         run: pnpm run test
